### ISSUE TITLE
Allow configuring the URL opened by 'subrpc endpoint open'

### ISSUE THREAD

**Issue by PierreBesson** [chevdor/subrpc#3]
SubRPC currently opens the browser on the following URL: `https://polkadot.js.org/apps/?rpc=$RPC_URL`.
For additional security, it should be possible to configure it to any value provided by the user for additional security of which UI you use.
Eg. useful alternative URL:
*  `https://cloudflare-ipfs.com/ipns/dotapps.io/?rpc=` or `https://ipfs.io/ipns/dotapps.io/?rpc=` (IPNS on Cloudflare/Protocol Labs gateways)
* `https://cloudflare-ipfs.com/ipfs/Qmc2fTXwJqY7hRn1jNG4h3hP251XnZjYjJPBF8RhMFyThq/?rpc=` (fixed polkadot.js version on IPFS).

**Comment by chevdor** [comment]
Indeed, I made the initial implementation simple and the ability to chose the site would be a good feature to have.

I think this can be done with:
- supporting a new flag/ENV such as `SUBRPC_BROWSER_URL` that would take values such as `https://cloudflare-ipfs.com/ipns/dotapps.io/?rpc={url}&some_other=flags`
- the ENV would default to the current `https://polkadot.js.org/apps/?rpc={url}`

So users could use a `.env` file or their `.bashrc`|`.zshrc` so set `SUBRPC_BROWSER_URL` or do a call such as:
```
SUBRPC_BROWSER_URL=https://cloudflare-ipfs.com/ipns/dotapps.io/?rpc={url}&some_other=flags  subrpc ep open westend
```

Would that work for you ?

**Comment by PierreBesson** [comment]
@chevdor Yes that would be perfect.
